name: Check index.html

on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for index.html
        run: |
          if [ -f index.html ]; then
            echo "index.html exists."
            exit 0
          else
            echo "index.html does not exist."
            exit 1
          fi
